"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import os
from setuptools import setup

relpath = os.path.dirname(__file__)
dataFolder = relpath + '/data'

APP = ['Filename Assistant.py']
DATA_FILES = [dataFolder]
OPTIONS = {
    'iconfile': relpath + '/data/icon.icns',
}

setup(
    app=APP,
    data_files=DATA_FILES, 
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
